import { describe, it, expect } from 'vitest';
import {
  projectShared,
  projectProjects,
  type SharedBrainDoc,
  type ProjectsBrainDoc,
} from '../../src/lib/brain-projections';

describe('projectShared', () => {
  it('produces the DO-NOT-HAND-EDIT banner', () => {
    const md = projectShared({});
    expect(md).toContain('GENERATED BY `pop brain snapshot`');
    expect(md).toContain('DO NOT HAND-EDIT');
  });

  it('handles empty doc without crashing', () => {
    const md = projectShared({});
    expect(typeof md).toBe('string');
    expect(md.length).toBeGreaterThan(0);
  });

  it('renders head CID when provided', () => {
    const md = projectShared({}, 'bafkreifakeheadcid');
    expect(md).toContain('bafkreifakeheadcid');
  });

  it('renders lesson with title + body', () => {
    const md = projectShared({
      lessons: [{ id: 'test1', author: '0xabc', title: 'Test Lesson', body: 'Test body content', timestamp: 1776400000 }],
    });
    expect(md).toContain('Test Lesson');
    expect(md).toContain('Test body content');
    expect(md).toContain('0xabc');
  });

  it('renders multiple lessons in order', () => {
    const md = projectShared({
      lessons: [
        { id: 'a', title: 'First', body: 'content A' },
        { id: 'b', title: 'Second', body: 'content B' },
        { id: 'c', title: 'Third', body: 'content C' },
      ],
    });
    const posA = md.indexOf('First');
    const posB = md.indexOf('Second');
    const posC = md.indexOf('Third');
    expect(posA).toBeGreaterThan(0);
    expect(posB).toBeGreaterThan(posA);
    expect(posC).toBeGreaterThan(posB);
  });

  it('handles lesson with `text` field (legacy name)', () => {
    const md = projectShared({
      lessons: [{ id: 'x', title: 'T', text: 'legacy text field' }],
    });
    expect(md).toContain('legacy text field');
  });

  it('handles lesson without title gracefully', () => {
    const md = projectShared({
      lessons: [{ id: 'nohdr', body: 'bodyonly' }],
    });
    expect(md).toContain('bodyonly');
    expect(typeof md).toBe('string');
  });

  it('accepts unix-seconds timestamp', () => {
    const md = projectShared({
      lessons: [{ id: 't', title: 'T', body: 'B', timestamp: 1776400000 }],
    });
    // Should render as ISO or formatted date (not crash on scale)
    expect(md).toContain('T');  // at minimum the title
  });

  it('accepts ISO-string timestamp', () => {
    const md = projectShared({
      lessons: [{ id: 't', title: 'T', body: 'B', timestamp: '2026-04-17T12:00:00Z' as any }],
    });
    expect(md).toContain('T');
  });

  it('is pure/idempotent — same input → byte-equal output', () => {
    const input: SharedBrainDoc = {
      lessons: [
        { id: 'lesson-1', author: '0xabc', title: 'Title', body: 'Body', timestamp: 1776400000 },
        { id: 'lesson-2', author: '0xdef', title: 'Title2', body: 'Body2', timestamp: 1776400100 },
      ],
    };
    const m1 = projectShared(input, 'cid1');
    const m2 = projectShared(input, 'cid1');
    expect(m1).toBe(m2);
  });

  it('handles rules + operatingConstraints fields if present', () => {
    const md = projectShared({
      rules: [{ id: 'r1', text: 'rule text' }],
      operatingConstraints: [{ constraint: 'oc text' }],
    });
    expect(typeof md).toBe('string');
    // Should render without crashing even for older schemas
  });

  it('handles unrecognized fields via JSON fallback (schema tolerance)', () => {
    const md = projectShared({
      lessons: [],
      futureUnknownField: { data: 'something novel' },
    } as any);
    expect(typeof md).toBe('string');
    expect(md.length).toBeGreaterThan(100);
  });
});

describe('projectProjects', () => {
  it('produces a DO-NOT-HAND-EDIT banner', () => {
    const md = projectProjects({} as ProjectsBrainDoc);
    expect(md).toContain('GENERATED BY `pop brain snapshot`');
  });

  it('handles empty projects doc', () => {
    const md = projectProjects({} as ProjectsBrainDoc);
    expect(typeof md).toBe('string');
    expect(md.length).toBeGreaterThan(0);
  });

  it('is pure/idempotent', () => {
    const input = { projects: [] } as any;
    const m1 = projectProjects(input);
    const m2 = projectProjects(input);
    expect(m1).toBe(m2);
  });
});
